### PR TITLE
travis: try to use precompiled SCIP on OS X

### PR DESCRIPTION
**Pull request by rschwarz**

### CODE REVIEW

**Comment by rschwarz** [comment]
[Travis can not find the `libscip.dylib`](https://travis-ci.org/SCIP-Interfaces/SCIP.jl/jobs/610513471#L187) of the precompiled SCIP:
```
┌ Error: Error building `SCIP`: 
│ ERROR: LoadError: Unable to locate SCIP installation.
│ Tried:
│ 	/Users/travis/build/SCIP-Interfaces/SCIP.jl/install/bin/libscip.dylib
│ 	/Users/travis/build/SCIP-Interfaces/SCIP.jl/install/lib/libscip.dylib
│ 	libscip.dylib
```
Just like in #142.

**Comment by fserra** [comment]
interesting. As a patch, maybe you can try adding the library path to `DYLD_LIBRARY_PATH`

**Comment by rschwarz** [comment]
> As a patch, maybe you can try adding the library path to DYLD_LIBRARY_PATH

This was not necessary before, when building SCIP from source. But feel free to try stuff :-) You should be able to push to this branch.

The current travis script does not print the actual contents of `install/lib`, but `libscip.dylib` should be there (I extracted locally).

**Comment by rschwarz** [comment]
In PR #110, when using the precompiled binaries on OS X, there was an illegal instruction in SoPlex/GMP. Maybe this is fixed with 6.0.2, or maybe some related problem is causing `dlopen` to fail.

**Pull request closed without merging**
