### PR TITLE
add Aqua tests

### PR DESCRIPTION
**Pull request by rschwarz**

### CODE REVIEW

**Comment by rschwarz** [comment]
Problem reported: https://github.com/JuliaLang/julia/issues/35909

**Comment by matbesancon** [comment]
TIL you could have compat bounds on a package that is only in your tests

**Comment by matbesancon** [comment]
no need anymore?

**Comment by rschwarz** [comment]
I guess there was never a *need* per se, I just wanted to try this out on another package that depends on SCIP but that failed with an error.

I understand that there is a bug in Julia itself causing the error. This might now be fixed in `master`, but to apply it to SCIP, we would have to require Julia ≥ 1.6, and I find that to be too restrictive for the sake of adding some generic tests.

**Pull request closed without merging**
